### PR TITLE
add cookie info

### LINKED ISSUE #43: Add Cookie Banner Keys
## Description
The cookie banner in the core repo introduces three new keys, we should reproduce them here.

## Plan
- [ ] Add the three keys to BrandCopy.elm, with the same string values

### PR DESCRIPTION
**Pull request by HedgehogHolly**
Fixes #43 

## Description

- added cookie bar keys

@neontribe/contemplating-action

### CODE REVIEW

**Review by katjam — APPROVED** [review]
Great! I can't wait for the banner.

**Comment by HedgehogHolly** [comment]
Can I merge even though it has build fails?

**Comment by katjam** [comment]
Probably wait. Or merge release into Nick's cookie branch and build against
that.

**Review by Nikomus — APPROVED** [review]
Very nice! 🍿

**Pull request merged**
