### PR TITLE
59 reference to therapy

### LINKED ISSUE #59: Change the reference to Therapy
## "Therapy"

Two mentions of "therapy" survived:

- [ ] In Gary's second picture
image
- [ ] In the alt text of Gary's third picture: Illustration of a confused man surrounded by thought bubbles. The bubbles contain Gary’s ideas of what Hope House was; there is a drawing of a therapy couch, two older people, a house and question marks.

### PR DESCRIPTION
**Pull request by HedgehogHolly**
Fixes #59 

## Description

- Add new image that has no reference to therapy
- Change alt text to make it clear that the therapy couch is a misconception 

@neontribe/contemplating-action

🐧

### CODE REVIEW

**Review by rosejbon — APPROVED** [review]
Perfecto

**Review by Nikomus — COMMENTED** [review]
The image is a little larger and a slightly different aspect ratio to the others.

**Comment by katjam** [comment]
We should probably re-open this and fix that. You beat me to it. Am assuming that is what #61 is about. :)

**Comment by HedgehogHolly** [comment]
I already have fixed this, theres a PR waiting for review.

**Comment by katjam** [comment]
Working up my emails bottom to top... good job. Pretend I wasn't here. :+1:

**Pull request merged**
